### ISSUE TITLE
handler-statuspage.rb:14:in `require': cannot load such file

### ISSUE THREAD

**Issue by oryband** [sensu-plugins/sensu-plugins-statuspage#3]
I'm getting this when using this handler plugin:
```Ruby
handler-statuspage.rb:14:in `require': cannot load such file -- redphone/statuspage (LoadError)\n\tfrom /usr/local/bundle/gems/sensu-plugins-statuspage-0.0.3/bin/handler-statuspage.rb:14:in `<top (required)>'\n\tfrom /usr/local/bundle/bin/handler-statuspage.rb:16:in `load'\n\tfrom /usr/local/bundle/bin/handler-statuspage.rb:16:in `<main>'\nonly handling every 30 occurrences: 
```
Note I've installed sensu manually and all its plugins using Bundler. But all other plugins and handlers (and sensu itself) are working fine.

See the Gemfile I'm using:
```Ruby
source 'https://rubygems.org'

gem 'sensu', '0.22.2'

# status page dependency, see
# https://github.com/sensu-plugins/sensu-plugins-statuspage#notes
#
# this installs the latest redphone as version 0.0.6 
gem 'redphone', '0.0.6', :github => 'portertech/redphone', :ref => 'cf5373df670263b25e7ab425c17ea773e66bdd85'

gem 'sensu-plugins-aws', '1.2.0'
gem 'sensu-plugins-couchbase', '0.2.0'
gem 'sensu-plugins-cpu-checks', '0.0.4'
gem 'sensu-plugins-disk-checks', '1.0.2'
gem 'sensu-plugins-dns', '0.0.6'
gem 'sensu-plugins-elasticsearch', '0.2.0'
gem 'sensu-plugins-filesystem-checks', '0.1.0'
gem 'sensu-plugins-graphite', '0.0.7'
gem 'sensu-plugins-hipchat', '0.0.3'
gem 'sensu-plugins-http', '0.1.2'
gem 'sensu-plugins-hubot', '0.0.2'
gem 'sensu-plugins-load-checks', '0.0.3'
gem 'sensu-plugins-mailer', '0.0.2'
gem 'sensu-plugins-memory-checks', '0.0.8'
gem 'sensu-plugins-network-checks', '0.0.6'
gem 'sensu-plugins-newrelic', '0.0.2'
gem 'sensu-plugins-nginx', '0.0.6'
gem 'sensu-plugins-process-checks', '0.0.6'
gem 'sensu-plugins-rabbitmq', '1.1.0'
gem 'sensu-plugins-redis', '0.0.4'
gem 'sensu-plugins-sensu', '0.0.2'
gem 'sensu-plugins-skyline', '0.0.2'
gem 'sensu-plugins-sms', '0.0.2'
gem 'sensu-plugins-statuspage', '0.0.3'
gem 'sensu-plugins-supervisor', '0.0.3'
gem 'sensu-plugins-syslog-ng', '0.0.2'
gem 'sensu-plugins-uchiwa', '0.0.3'
gem 'sensu-plugins-uptime-checks', '0.0.3'
gem 'sensu-plugins-victorops', '0.1.0'
gem 'sensu-plugins-wordpress', '0.0.2'
gem 'sensu-plugins-xmpp', '0.0.3'
```

**Comment by oryband** [comment]
In addition, [redphone hasn't been updated in 4 (!) years](https://github.com/jaxxstorm/redphone/releases). Maybe this plugin should it as a dependency entirely, since [it forces an unconventional way of installing itself](https://github.com/sensu-plugins/sensu-plugins-statuspage#notes).

**Comment by analytically** [comment]
I'll happily accept a PR!

**Comment by andresgutgon** [comment]
@analytically what would be the idea here? How can be done this if redphone's author does not publish the new version?
